[34m[1mwandb[39m[22m: [33mWARNING[39m Calling wandb.run.save without any arguments is deprecated.Changes to attributes are automatically persisted.
INFO flower 2022-03-17 13:20:14,977 | app.py:61 | Opened (insecure) gRPC connection
DEBUG flower 2022-03-17 13:20:14,981 | connection.py:36 | ChannelConnectivity.IDLE
DEBUG flower 2022-03-17 13:20:15,187 | connection.py:68 | Insecure gRPC channel closed
Traceback (most recent call last):
  File "src/client.py", line 125, in <module>
    main(args)
  File "src/client.py", line 113, in main
    fl.client.start_numpy_client("[::]:8080", client=CifarClient())
  File "/Users/villadsstokbro/opt/anaconda3/envs/flower_tut/lib/python3.8/site-packages/flwr/client/app.py", line 112, in start_numpy_client
    start_client(
  File "/Users/villadsstokbro/opt/anaconda3/envs/flower_tut/lib/python3.8/site-packages/flwr/client/app.py", line 64, in start_client
    server_message = receive()
  File "/Users/villadsstokbro/opt/anaconda3/envs/flower_tut/lib/python3.8/site-packages/flwr/client/grpc_client/connection.py", line 60, in <lambda>
    receive: Callable[[], ServerMessage] = lambda: next(server_message_iterator)
  File "/Users/villadsstokbro/opt/anaconda3/envs/flower_tut/lib/python3.8/site-packages/grpc/_channel.py", line 426, in __next__
    return self._next()
  File "/Users/villadsstokbro/opt/anaconda3/envs/flower_tut/lib/python3.8/site-packages/grpc/_channel.py", line 826, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1647519614.976051000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3129,"referenced_errors":[{"created":"@1647519614.976050000","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":163,"grpc_status":14}]}"
>